---

- name: Installing fish formulas
  homebrew:
    name: "{{ fish_formulas}}"
    state: present
  when: fish_formulas | list
  tags:
    - fish

- name: Upgrading fish formulas
  homebrew:
    name: "{{ fish_formulas}}"
    state: latest
    update_homebrew: yes
  when: fish_formulas | list
  tags:
    - upgrade

- name: Creating fish configuration directory
  file:
    path: "{{ ansible_env.HOME }}/.config/fish"
    recurse: yes
    state: directory
  when: fish_config_source_path | string
  tags:
    - fish

- name: Updating fish configurations folder
  copy:
    src: "{{ fish_config_source_path }}"
    dest: "{{ ansible_env.HOME }}/.config"
  when: fish_config_source_path | string
  tags:
    - fish

- name: Creating fisherman install directory
  file:
    dest: "{{ ansible_env.HOME }}/.config/fish/functions"
    recurse: yes
    state: directory
  when: fish_formulas | list
  tags:
    - fish

- name: Installing fisherman
  get_url:
    url: https://git.io/fisher
    dest: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
  when: fish_formulas | list
  tags:
    - fish

- name: Retrieving installed fisherman packages
  shell: fisher list
  args:
    executable: /usr/local/bin/fish
  register: fisherman_plugins
  changed_when: false
  failed_when: false
  tags:   # This needs fish
    - skip_ansible_lint
    - fish
  when: fish_formulas | list

- name: Installing fish plugins
  shell: fisher install {{ item }}
  args:
    executable: /usr/local/bin/fish
  with_items: "{{ fish_plugins }}"
  when: "fish_formulas | list and item not in fisherman_plugins.stdout"
  tags:   # This needs fish
    - skip_ansible_lint
    - fish

- name: Updating theme configuration
  copy:
    src: "{{ fish_starship_source_path }}"
    dest: "{{ ansible_env.HOME }}/.config/starship.toml"
  when: fish_starship_source_path | string
  tags:
    - fish

- name: Adding fish to shells
  lineinfile:
    path: /etc/shells
    regexp: '^/usr/local/bin/fish'
    line: '/usr/local/bin/fish'
  become: true
  become_user: root
  tags:
    - shell

- name: Changing login shell to fish
  command: chsh -s /usr/local/bin/fish
  changed_when: false
  when: lookup('env','SHELL') != "/usr/local/bin/fish"
  tags:
    - shell
